// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!


// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters


import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;


const _$jniVersionCheck =
    jni$_.JniVersionCheck(1, 0);

/// from: `io.github.iot_gamer.hand_landmarker.MyHandLandmarker`
extension type MyHandLandmarker._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'io/github/iot_gamer/hand_landmarker/MyHandLandmarker');

      /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MyHandLandmarker> type = $MyHandLandmarker$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Landroid/content/Context;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions
    .lookup<jni$_.NativeFunction<jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>('globalEnv_NewObject')
    .asFunction<jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();
  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory MyHandLandmarker(jni$_.JObject context, ) {
    final _$context = context.reference;
    return _new$(_class.reference.pointer, _id_new$.pointer, _$context.pointer).object<MyHandLandmarker>();
  }

}
  extension MyHandLandmarker$$Methods on MyHandLandmarker {
      static final _id_initialize = MyHandLandmarker._class.instanceMethodId(
    r'initialize',
    r'(IFZ)V',
  );

  static final _initialize = jni$_.ProtectedJniExtensions
    .lookup<jni$_.NativeFunction<jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, jni$_.VarArgs<(jni$_.Int32, jni$_.Double, jni$_.Int32)>)>>('globalEnv_CallVoidMethod')
    .asFunction<jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, core$_.int, core$_.double, core$_.int)>();
  /// from: `public fun initialize(numHands: kotlin.Int, minHandDetectionConfidence: kotlin.Float, useGpu: kotlin.Boolean): kotlin.Unit`
  void initialize(core$_.int i, core$_.double f, core$_.bool z, ){
    
    _initialize(reference.pointer, _id_initialize.pointer, i, f, z ? 1 : 0).check();
  }

  static final _id_detectFromYuv = MyHandLandmarker._class.instanceMethodId(
    r'detectFromYuv',
    r'(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIII)Ljava/lang/String;',
  );

  static final _detectFromYuv = jni$_.ProtectedJniExtensions
    .lookup<jni$_.NativeFunction<jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32, jni$_.Int32, jni$_.Int32, jni$_.Int32, jni$_.Int32)>)>>('globalEnv_CallObjectMethod')
    .asFunction<jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>, core$_.int, core$_.int, core$_.int, core$_.int, core$_.int, core$_.int)>();
  /// from: `public fun detectFromYuv(yBuffer: java.nio.ByteBuffer, uBuffer: java.nio.ByteBuffer, vBuffer: java.nio.ByteBuffer, width: kotlin.Int, height: kotlin.Int, yRowStride: kotlin.Int, uvRowStride: kotlin.Int, uvPixelStride: kotlin.Int, rotation: kotlin.Int): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString detectFromYuv(jni$_.JByteBuffer byteBuffer, jni$_.JByteBuffer byteBuffer1, jni$_.JByteBuffer byteBuffer2, core$_.int i, core$_.int i1, core$_.int i2, core$_.int i3, core$_.int i4, core$_.int i5, ){
    final _$byteBuffer = byteBuffer.reference;
    final _$byteBuffer1 = byteBuffer1.reference;
    final _$byteBuffer2 = byteBuffer2.reference;
    return _detectFromYuv(reference.pointer, _id_detectFromYuv.pointer, _$byteBuffer.pointer, _$byteBuffer1.pointer, _$byteBuffer2.pointer, i, i1, i2, i3, i4, i5).object<jni$_.JString>();
  }


  }
  final class $MyHandLandmarker$Type$ extends jni$_.JType<MyHandLandmarker> {
  @jni$_.internal
  const $MyHandLandmarker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/github/iot_gamer/hand_landmarker/MyHandLandmarker;';
}

